print('Pick a number between 1 and 10')
a=input('Press the enter key to continue')
print('Multiply that number by two')
a=input('Press the enter key to continue')
print('Multiply by 5 next')
a=input('Press the enter key to continue')
print('Divide the current number by the original number')
a=input('Press the enter key to continue')
print('Subtract 7 from the current number')
a=input('Press the enter key to continue')
print(' ')
print('Is that number 3?')